import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Coffee } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  SignOutButton,
} from "@clerk/nextjs";
import { ClerkUsername } from "./hooks/useUsername";
import UserDataSync from "./actions/UserDataSync";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <UserDataSync />
          <div className="flex font-bold px-20 pt-10 w-[98vw] justify-between absolute top-0">
            <div className="flex">
              <Coffee /> Buy me coffee
            </div>
            <SignedIn>
              <div className="flex items-center justify-around space-x-5">
                <UserButton />
                <ClerkUsername />
                <SignOutButton redirectUrl="/">
                  <Button className="text-[16px] border cursor-pointer hover:bg-red-300">Sign Out</Button>
                </SignOutButton>
              </div>
            </SignedIn>
          </div>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
